CREATE DATABASE tp_comments CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE tp_comments;

CREATE TABLE comments (
id INT AUTO_INCREMENT PRIMARY KEY,
content TEXT NOT NULL,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;